CREATE TABLE IF NOT EXISTS ORDERS (
ORDER_ID TEXT,
PRODUCT_NAME,
QUANTITY INTEGER,
PRICE REAL 
);

INSERT INTO ORDERS(ORDER_ID, PRODUCT_NAME, QUANTITY, PRICE) VALUES
('01', 'PEN', 10, 50),
('02', 'BOOK', 5, 100),
('03', 'PEN', 8, 40),
('04', 'PENCIL', 15, 30);

SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;

SELECT AVG(PRICE) AS AVERAGE_PRICE 
FROM ORDERS;

SELECT PRODUCT_NAME , SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS
GROUP BY PRODUCT_NAME;


